/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.qyouti.treeoftrust.gui;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JScrollPane;
import org.bouncycastle.openpgp.PGPPublicKey;
import org.bouncycastle.openpgp.PGPSecretKey;
import org.bouncycastle.openpgp.PGPSignature;
import org.bouncycastle.openpgp.PGPSignatureSubpacketVector;
import org.qyouti.treeoftrust.CryptographyManager;
import org.qyouti.treeoftrust.SignatureVerificationResultSet;


/**
 *
 * @author maber01
 */
public class KeyPanel
        extends javax.swing.JPanel
{
  PGPSecretKey seckey;
  PGPPublicKey pubkey;
  boolean winprotect;
  
  private static final DateFormat df = new SimpleDateFormat( "HH:mm dd/MMM/yyyy" );
  
  /**
   * Creates new form SecretKeyPanel
   * @param seckey
   * @param pubkey
   * @param signatureverificationresultset
   * @param winprotect
   */
  public KeyPanel( PGPSecretKey seckey, PGPPublicKey pubkey, SignatureVerificationResultSet signatureverificationresultset, boolean winprotect )
  {
    this.seckey = seckey;
    this.pubkey = pubkey;
    this.winprotect = winprotect;
    if ( pubkey == null && seckey != null )
      pubkey = seckey.getPublicKey();
    
    initComponents();
    namelabel.setText( pubkey.getUserIDs().next() );
    idlabel.setText( Long.toHexString( pubkey.getKeyID() ) );
    fingerprintlabel.setText( CryptographyManager.prettyPrintFingerprint( pubkey.getFingerprint() ) );
    if ( seckey != null )
      protectionlabel.setText( winprotect?"Protected by Windows Cryptography":"Protected by password which you must remember");
    else
      protectionlabel.setText( "Public key only - contains no secret data." );
    creationdatelabel.setText( "?" );
    Date d = CryptographyManager.getKeyCreationDate( pubkey );
    if ( d != null )
      creationdatelabel.setText( df.format(d) );
    
    Iterator it = pubkey.getSignatures();
    for ( int i=0; it.hasNext(); i++ )
    {
      PGPSignature sig = (PGPSignature)it.next();
      sig.getKeyID();
      JScrollPane sigscrollpane = new JScrollPane();
      SignaturePanel sigpanel = new SignaturePanel( sig, signatureverificationresultset.getSignatureVerificationResultAt(i) );
      sigscrollpane.setViewportView( sigpanel );
      signaturetabbedpane.add( Long.toHexString( sig.getKeyID() ).toUpperCase(), sigscrollpane );
    }
  }

  public PGPSecretKey getSecretKey()
  {
    return seckey;
  }

  
  
  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jLabel7 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    creationdatelabel = new javax.swing.JLabel();
    namelabel = new javax.swing.JLabel();
    idlabel = new javax.swing.JLabel();
    fingerprintlabel = new javax.swing.JLabel();
    protectionlabel = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    signaturetabbedpane = new javax.swing.JTabbedPane();

    setMinimumSize(new java.awt.Dimension(500, 300));

    jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    jLabel7.setText("Date of Creation:");

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    jLabel1.setText("Key pair ID:");

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    jLabel2.setText("Owner Name:");

    jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    jLabel3.setText("Fingerprint:");

    jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    jLabel4.setText("Protection:");

    creationdatelabel.setText("...");

    namelabel.setText("...");

    idlabel.setText("...");

    fingerprintlabel.setText("...");

    protectionlabel.setText("...");

    jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    jLabel6.setText("Certifications:");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jLabel6)
          .addComponent(jLabel4)
          .addComponent(jLabel1)
          .addComponent(jLabel2)
          .addComponent(jLabel3)
          .addComponent(jLabel7))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(namelabel, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
          .addComponent(idlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(fingerprintlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(protectionlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(creationdatelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
      .addComponent(signaturetabbedpane)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel7)
          .addComponent(creationdatelabel))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(namelabel)
          .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(idlabel))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(fingerprintlabel))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(protectionlabel))
        .addGap(18, 18, 18)
        .addComponent(jLabel6)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(signaturetabbedpane, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel creationdatelabel;
  private javax.swing.JLabel fingerprintlabel;
  private javax.swing.JLabel idlabel;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel namelabel;
  private javax.swing.JLabel protectionlabel;
  private javax.swing.JTabbedPane signaturetabbedpane;
  // End of variables declaration//GEN-END:variables
}
