/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.qyouti.treeoftrust.gui;

import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.TreePath;
import org.qyouti.treeoftrust.KeyRingCollectionTreeModel;
import org.qyouti.treeoftrust.PublicKeyNode;
import org.qyouti.treeoftrust.SecretKeyNode;
import org.qyouti.treeoftrust.SignatureVerificationResultSet;
import org.qyouti.treeoftrust.TreeOfTrust;
import org.qyouti.treeoftrust.TreeOfTrustNode;

/**
 *
 * @author jon
 */
public class KeyRingCollectionPanel extends javax.swing.JPanel
        implements TreeSelectionListener
{
  KeyRingCollectionTreeModel treemodel;

  
  /**
   * Creates new form TreeOfTrustPanel
   */
  public KeyRingCollectionPanel()
  {
    initComponents();
    tree.addTreeSelectionListener( this );
  }

  public KeyRingCollectionTreeModel getKeyRingCollectionTreeModel()
  {
    return treemodel;
  }

  public void setKeyRingCollectionTreeModel( KeyRingCollectionTreeModel treemodel )
  {
    this.treemodel = treemodel;
    tree.setModel( treemodel );
    tree.setCellRenderer( new TreeNodeRenderer() );
  }

  @Override
  public void valueChanged(TreeSelectionEvent e)
  {
    System.out.println( "Select " + e.getPath() );
    TreePath p = e.getPath();
    if ( p != null && p.getLastPathComponent() instanceof SecretKeyNode )
    {
      SecretKeyNode n = (SecretKeyNode)p.getLastPathComponent();
      nodelscrollpanel.setViewportView( new KeyPanel( n.getSecretKey(), n.getSecretKey().getPublicKey(), new SignatureVerificationResultSet(), n.hasWindowsPassword() ) );
      return;
    }
    if ( p != null && p.getLastPathComponent() instanceof PublicKeyNode )
    {
      PublicKeyNode n = (PublicKeyNode)p.getLastPathComponent();
      nodelscrollpanel.setViewportView( new KeyPanel( null, n.getPublicKey(), new SignatureVerificationResultSet(), false ) );
      return;
    }
    nodelscrollpanel.setViewportView(null);
  }
  
  
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jSplitPane1 = new javax.swing.JSplitPane();
    jScrollPane1 = new javax.swing.JScrollPane();
    tree = new javax.swing.JTree();
    nodelscrollpanel = new javax.swing.JScrollPane();

    setLayout(new java.awt.BorderLayout());

    jSplitPane1.setDividerLocation(250);
    jSplitPane1.setDividerSize(16);

    tree.setRootVisible(false);
    jScrollPane1.setViewportView(tree);

    jSplitPane1.setLeftComponent(jScrollPane1);
    jSplitPane1.setRightComponent(nodelscrollpanel);

    add(jSplitPane1, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JSplitPane jSplitPane1;
  private javax.swing.JScrollPane nodelscrollpanel;
  private javax.swing.JTree tree;
  // End of variables declaration//GEN-END:variables

}
